version: 2

tasks:
  run:
    sources: ["Functions/**/*.cs"]
    generates: ["Function/bin/output/bin/Transferwise.dll"]
    cmds:
    - func start --build
    dir: Functions
  generate-api:
    cmds:
      - openapi-generator generate -i spec.yml -o APIs/Transferwise -g csharp-netcore -c openapi.config.yml
      - dotnet add Functions/TransferWise.csproj reference APIs/Transferwise/src/Transferwise.Services/Transferwise.Services.csproj
    dir: openapi/transferwise
  generate-api:crunch:
    cmds:
      - openapi-generator generate -i spec.yml -o APIs/Crunch -g csharp-netcore -c openapi.config.yml
      - dotnet add Functions/TransferWise.csproj reference APIs/Crunch/src/Crunch.Services/Crunch.Services.csproj
    dir: openapi/crunch
