/* 
 * Transferwise
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Transferwise.Services.Api;
using Transferwise.Services.Model;
using Transferwise.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Transferwise.Services.Test
{
    /// <summary>
    ///  Class for testing StateChange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StateChangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StateChange
        //private StateChange instance;

        public StateChangeTests()
        {
            // TODO uncomment below to create an instance of StateChange
            //instance = new StateChange();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StateChange
        /// </summary>
        [Fact]
        public void StateChangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StateChange
            //Assert.IsInstanceOfType<StateChange> (instance, "variable 'instance' is a StateChange");
        }


        /// <summary>
        /// Test the property 'CurrentState'
        /// </summary>
        [Fact]
        public void CurrentStateTest()
        {
            // TODO unit test for the property 'CurrentState'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Fact]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'OccuredAt'
        /// </summary>
        [Fact]
        public void OccuredAtTest()
        {
            // TODO unit test for the property 'OccuredAt'
        }

    }

}
