/* 
 * Transferwise
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Transferwise.Services.Api;
using Transferwise.Services.Model;
using Transferwise.Services.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Transferwise.Services.Test
{
    /// <summary>
    ///  Class for testing Transfer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransferTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Transfer
        //private Transfer instance;

        public TransferTests()
        {
            // TODO uncomment below to create an instance of Transfer
            //instance = new Transfer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Transfer
        /// </summary>
        [Fact]
        public void TransferInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Transfer
            //Assert.IsInstanceOfType<Transfer> (instance, "variable 'instance' is a Transfer");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'TargetAccount'
        /// </summary>
        [Fact]
        public void TargetAccountTest()
        {
            // TODO unit test for the property 'TargetAccount'
        }
        /// <summary>
        /// Test the property 'SourceAccount'
        /// </summary>
        [Fact]
        public void SourceAccountTest()
        {
            // TODO unit test for the property 'SourceAccount'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'SourceValue'
        /// </summary>
        [Fact]
        public void SourceValueTest()
        {
            // TODO unit test for the property 'SourceValue'
        }
        /// <summary>
        /// Test the property 'SourceCurrency'
        /// </summary>
        [Fact]
        public void SourceCurrencyTest()
        {
            // TODO unit test for the property 'SourceCurrency'
        }
        /// <summary>
        /// Test the property 'TargetValue'
        /// </summary>
        [Fact]
        public void TargetValueTest()
        {
            // TODO unit test for the property 'TargetValue'
        }
        /// <summary>
        /// Test the property 'TargetCurrency'
        /// </summary>
        [Fact]
        public void TargetCurrencyTest()
        {
            // TODO unit test for the property 'TargetCurrency'
        }

    }

}
